[deps]
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
GerryChain = "e09a5c58-8952-4b57-bc02-56d902e45e6e"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
